### ISSUE TITLE
Support for Animated webm/webp

### ISSUE THREAD

**Issue by brunocalado** [EddieDover/Theater-of-the-Mind#43]
**Is your feature request related to a problem? Please describe.**
Allow the use of animated webm/webp. 

**Demo**
https://github.com/EddieDover/Theater-of-the-Mind/assets/4999783/79ec8e41-af49-4348-99f4-ca5383b046c2

**Describe alternatives you've considered**
I could just use the actor sheet art, but I have some animated webp too.

**Comment by EddieDover** [comment]
Foundry itself doesn't support webm files but it does support webp.

I'll see about adding a default icon so the broken image link is no longer seen but there's not much I can do about this until Foundry catches up with the times.
